# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: code_hard | drink_hard 
email: the.booneage@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Musings and observations of a self-proclaimed programmer.
url: http://www.codehard-drinkhard.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jonathaneboone
github_username:  boonej
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

permalink     : /:year/:title/
highlighter   : pygments

title         : code hard | drink hard

author:
  name        : JB Boone
  job         : serious programmer
  thumb       : "https://en.gravatar.com/userimage/7218333/b42e92103062c7b1f1f6a2b6d5a05154.jpeg"
  email       : the.booneage@gmail.com
  url         : http://www.codehard-drinkhard.com
  github      : http://github.com/boonej
  twitter     : http://twitter.com/jonathaneboone
  facebook    : http://facebook.com/boonej
  linkedin    : http://linkedin.com/in/boonej
